name: Docker Image Downloader (Prom & Grafana)

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Images
        run: |
          docker pull prom/prometheus:latest
          docker pull grafana/grafana:latest
          
      - name: Save Images to TAR
        run: |
          # 두 이미지를 하나의 tar 파일로 묶어서 저장합니다.
          docker save prom/prometheus:latest grafana/grafana:latest -o monitoring_images.tar
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: monitoring-stack-images
          path: monitoring_images.tar
          retention-days: 1
