name: Docker Image Downloader (postgres:18)

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Images
        run: |
          docker pull postgres:18-alphine
          
      - name: Save Images to TAR
        run: |
          docker save postgres:18-alphine postgres18.tar
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: postgres18
          path: postgres18.tar
          retention-days: 1
