name: Download RHEL CIFS RPMs

on:
  workflow_dispatch:

jobs:
  extract-rpms:
    runs-on: ubuntu-latest
    steps:
      - name: Create Directory
        run: mkdir -p rhel_rpms

      - name: Download RPMs from RHEL UBI
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/rhel_rpms:/downloads \
            ://registry.access.redhat.com \
            bash -c "dnf install -y 'dnf-command(download)' && dnf download --resolve --alldeps --destdir=/downloads cifs-utils"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rhel-cifs-package-bundle
          path: rhel_rpms/
          retention-days: 1
